import type { Metadata } from "next";
import "./globals.css";
import { poppinsFontClass } from "@lib/theme/fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsFontClass.className}`}>{children}</body>
    </html>
  );
}
